### ISSUE TITLE
unknown_keywords not synchronized with schema structure

### ISSUE THREAD

**Issue by DanFulger** [pboettch/json-schema-validator#143]
The unknown_keywords variable in json-validator.cpp is created gradually, by using operator[] with JSON pointers.
This fails for some schemas when:
- the first property of an object looks like a number (and operator[] creates array when it should create object)
- the second property does not look like a number.
I'm not an expert, the only way I see is to create the parents manually instead of relying on operator[] with JSON pointer parameter.

The validator fails to load a valid schema because of this.
Example:
```JSON
{
    "properties": {
        "123": { 
            "examples": [ "something" ]
        },
        "abc": {
            "examples": [ "something" ]
        }
    }
}
```

**Comment by pboettch** [comment]
You can inline JSON here with ```JSON ...  ``` (three dots are lines actually)

**Comment by pboettch** [comment]
I reduced your schema to

```JSON
{
    "1": {
    },
    "a": {
    }
}    
```

**Comment by pboettch** [comment]
OK, I understood what you mean with `operator[] with JSON-pointers`.

Basically this pure nlohmann::json-code will failed:

```C++
#include <nlohmann/json.hpp>

int main(void)
{
    nlohmann::json j;
    j["/obj/1"_json_pointer] = 1;
    j["/obj/a"_json_pointer] = 2;
    return 0;
}
```
Because the first json-pointer "/obj/1" makes it create obj as an array.

What does the standard say? 👀  It does not detail this ambiguity.

That means, it has to be handled manually, probably in nlohmann::json. If instance is an object, 0 is actually "0", otherwise if array, it's zero.

**Comment by pboettch** [comment]
I fixed it inside this library: as unknown-keywords are always objects, we can easily force it.

**Comment by pboettch** [comment]
And there is no issue with nlohmann::json:

```C++
#include <nlohmann/json.hpp>

#include <iostream>

int main(void)
{
    nlohmann::json j;
    j["obj"] = {10, 20, 30};

    std::cout << j << ": " << j["/obj/1"_json_pointer] << "\n";

    j["obj"] = {{"1", 20}, {"2", 30}};
    std::cout << j << ": " << j["/obj/1"_json_pointer] << "\n";

    return 0;
}
```

**Comment by DanFulger** [comment]
The original schema still fails, it's the multiple levels that require doing this parent by parent:
```
> ./json-install/bin/json-schema-validate issue_143.json
setting root schema failed
[json.exception.parse_error.109] parse error: array index 'abc' is not a number
```

**Comment by pboettch** [comment]
Could you try the fix-143-branch whether this works for your real-world-schema?

Sorry for the inconvenience with the first incomplete fix.

**Comment by DanFulger** [comment]
Thank you very much, it's working now!

**Comment by DanFulger** [comment]
You forgot #include <deque>; gcc compiled ok, but Visual C++ needs the include.

**Comment by pboettch** [comment]
Thanks, I added it. Now missing only the tests.
